import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
@Injectable()
export class WishlistService {
  constructor(private readonly prisma: PrismaService) {}
  private get(userId:string){ return this.prisma.wishlist.upsert({where:{userId},create:{userId},update:{},include:{items:{include:{product:true,variant:true}}}}); }
  list(userId:string){return this.get(userId);}
  async add(userId:string,b:any){const p=await this.prisma.product.findFirst({where:{id:b.productId,status:'ACTIVE',publishedAt:{not:null}},include:{variants:true}});if(!p)throw new NotFoundException('Product not found or inactive');if(b.variantId&&!p.variants.some(v=>v.id===b.variantId&&v.status==='ACTIVE'))throw new NotFoundException('Variant not found or inactive');const w=await this.get(userId);try{await this.prisma.wishlistItem.create({data:{wishlistId:w.id,productId:p.id,variantId:b.variantId}})}catch(e:any){if(e.code==='P2002')throw new BadRequestException('Product already in wishlist');throw e;}return this.get(userId);}
  async remove(userId:string,id:string){const w=await this.get(userId);if(!w.items.some(i=>i.id===id))throw new NotFoundException('Wishlist item not found');await this.prisma.wishlistItem.delete({where:{id}});return this.get(userId);}
  async moveToCart(userId:string,id:string){const w=await this.get(userId);const item=w.items.find(i=>i.id===id);if(!item)throw new NotFoundException('Wishlist item not found');const p=await this.prisma.product.findFirst({where:{id:item.productId,status:'ACTIVE',publishedAt:{not:null}},include:{variants:true}});if(!p)throw new BadRequestException('Product is no longer available');const v=item.variantId?p.variants.find(x=>x.id===item.variantId&&x.status==='ACTIVE'):null;if(item.variantId&&!v)throw new BadRequestException('Variant is no longer available');const cart=await this.prisma.cart.upsert({where:{userId_status:{userId,status:'ACTIVE'}},create:{userId},update:{}});const existing=await this.prisma.cartItem.findFirst({where:{cartId:cart.id,productId:item.productId,variantId:item.variantId}});if(existing)await this.prisma.cartItem.update({where:{id:existing.id},data:{quantity:Math.min(99,existing.quantity+1)}});else await this.prisma.cartItem.create({data:{cartId:cart.id,productId:item.productId,variantId:item.variantId,quantity:1,unitPriceSnapshot:v?.price??p.basePrice}});await this.prisma.wishlistItem.delete({where:{id}});return {cartId:cart.id};}
}
