import Link from 'next/link';
import { productsApi } from '@/lib/api/products.api';
import { ProductGrid } from '@/components/catalog/product-grid';
import { categoriesApi } from '@/lib/api/categories.api';
import { brandsApi } from '@/lib/api/brands.api';

export const dynamic = 'force-dynamic';

export default async function SearchPage({ searchParams }: { searchParams?: Promise<Record<string, string | undefined>> }) {
  const params = (await searchParams) ?? {};
  const query = params.q?.trim();
  const [products, categories, brands] = await Promise.all([productsApi.search({ q: query, page: Number(params.page ?? 1), limit: 12, category: params.category, brand: params.brand, minPrice: params.minPrice ? Number(params.minPrice) : undefined, maxPrice: params.maxPrice ? Number(params.maxPrice) : undefined, productType: params.productType as never, featured: params.featured === 'true' ? true : undefined, sort: params.sort as never }), categoriesApi.list({ limit: 50 }), brandsApi.list({ limit: 50 })]);
  const base = new URLSearchParams(Object.entries(params).filter((entry): entry is [string, string] => Boolean(entry[1])));
  return <main className="mx-auto max-w-7xl px-4 py-10"><div className="mb-8"><p className="text-sm font-medium text-muted-foreground">Discovery</p><h1 className="text-3xl font-bold">Search products</h1><form className="mt-5 grid gap-2 md:grid-cols-4"><input name="q" defaultValue={query} placeholder="Search by product, brand, or category" className="rounded-md border bg-background px-3 py-2 md:col-span-2" /><select name="category" defaultValue={params.category ?? ''} className="rounded-md border bg-background px-3 py-2"><option value="">All categories</option>{categories.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="brand" defaultValue={params.brand ?? ''} className="rounded-md border bg-background px-3 py-2"><option value="">All brands</option>{brands.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="minPrice" type="number" min="0" defaultValue={params.minPrice} placeholder="Min price" className="rounded-md border bg-background px-3 py-2" /><input name="maxPrice" type="number" min="0" defaultValue={params.maxPrice} placeholder="Max price" className="rounded-md border bg-background px-3 py-2" /><select name="productType" defaultValue={params.productType ?? ''} className="rounded-md border bg-background px-3 py-2"><option value="">All product types</option><option value="SIMPLE">Simple</option><option value="VARIABLE">Variable</option></select><select name="sort" defaultValue={params.sort ?? 'newest'} className="rounded-md border bg-background px-3 py-2"><option value="relevance">Relevance</option><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="price_asc">Price low to high</option><option value="price_desc">Price high to low</option><option value="name_asc">Name A-Z</option><option value="name_desc">Name Z-A</option></select><label className="flex items-center gap-2 px-2 text-sm"><input name="featured" value="true" type="checkbox" defaultChecked={params.featured === 'true'} /> Featured only</label><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground">Apply filters</button><Link href="/search" className="rounded-md border px-4 py-2 text-center">Clear all</Link></form></div>{query ? <p className="mb-4 text-sm text-muted-foreground">Results for “{query}” · {products.total} products</p> : null}<ProductGrid products={products.items} />{products.totalPages > 1 ? <div className="mt-8 flex gap-3">{products.page > 1 ? <Link className="underline" href={`/search?${new URLSearchParams([...base, ['page', String(products.page - 1)]])}`}>Previous</Link> : null}{products.page < products.totalPages ? <Link className="underline" href={`/search?${new URLSearchParams([...base, ['page', String(products.page + 1)]])}`}>Next</Link> : null}</div> : null}</main>;
}
